/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const TradeLog = IDL.Record({
  'status' : TradeStatus,
  'tokenId' : IDL.Text,
  'tradeType' : TradeType,
  'amountToken' : IDL.Float64,
  'timestamp' : IDL.Int,
  'amountBtc' : IDL.Float64,
  'price' : IDL.Float64,
});
export const Strategy = IDL.Record({
  'active' : IDL.Bool,
  'tokenId' : IDL.Text,
  'tradeType' : TradeType,
  'name' : IDL.Text,
  'autoRepeat' : IDL.Bool,
  'stopLoss' : IDL.Float64,
  'maxTradeSize' : IDL.Float64,
  'priceTarget' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTradeLog' : IDL.Func([TradeLog], [], []),
  'createOrUpdateStrategy' : IDL.Func([Strategy], [], []),
  'deleteStrategy' : IDL.Func([IDL.Text], [], []),
  'getTradeLogs' : IDL.Func([], [IDL.Vec(TradeLog)], ['query']),
  'listStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
  'toggleStrategyActive' : IDL.Func([IDL.Text], [Strategy], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const TradeLog = IDL.Record({
    'status' : TradeStatus,
    'tokenId' : IDL.Text,
    'tradeType' : TradeType,
    'amountToken' : IDL.Float64,
    'timestamp' : IDL.Int,
    'amountBtc' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const Strategy = IDL.Record({
    'active' : IDL.Bool,
    'tokenId' : IDL.Text,
    'tradeType' : TradeType,
    'name' : IDL.Text,
    'autoRepeat' : IDL.Bool,
    'stopLoss' : IDL.Float64,
    'maxTradeSize' : IDL.Float64,
    'priceTarget' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTradeLog' : IDL.Func([TradeLog], [], []),
    'createOrUpdateStrategy' : IDL.Func([Strategy], [], []),
    'deleteStrategy' : IDL.Func([IDL.Text], [], []),
    'getTradeLogs' : IDL.Func([], [IDL.Vec(TradeLog)], ['query']),
    'listStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
    'toggleStrategyActive' : IDL.Func([IDL.Text], [Strategy], []),
  });
};

export const init = ({ IDL }) => { return []; };