/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Strategy {
  'active' : boolean,
  'tokenId' : string,
  'tradeType' : TradeType,
  'name' : string,
  'autoRepeat' : boolean,
  'stopLoss' : number,
  'maxTradeSize' : number,
  'priceTarget' : number,
}
export interface TradeLog {
  'status' : TradeStatus,
  'tokenId' : string,
  'tradeType' : TradeType,
  'amountToken' : number,
  'timestamp' : bigint,
  'amountBtc' : number,
  'price' : number,
}
export type TradeStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export interface _SERVICE {
  'addTradeLog' : ActorMethod<[TradeLog], undefined>,
  'createOrUpdateStrategy' : ActorMethod<[Strategy], undefined>,
  'deleteStrategy' : ActorMethod<[string], undefined>,
  'getTradeLogs' : ActorMethod<[], Array<TradeLog>>,
  'listStrategies' : ActorMethod<[], Array<Strategy>>,
  'toggleStrategyActive' : ActorMethod<[string], Strategy>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];