/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradeLog {
    status: TradeStatus;
    tokenId: string;
    tradeType: TradeType;
    amountToken: number;
    timestamp: bigint;
    amountBtc: number;
    price: number;
}
export interface Strategy {
    active: boolean;
    tokenId: string;
    tradeType: TradeType;
    name: string;
    autoRepeat: boolean;
    stopLoss: number;
    maxTradeSize: number;
    priceTarget: number;
}
export enum TradeStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TradeType {
    buy = "buy",
    sell = "sell"
}
export interface backendInterface {
    addTradeLog(log: TradeLog): Promise<void>;
    createOrUpdateStrategy(strategy: Strategy): Promise<void>;
    deleteStrategy(name: string): Promise<void>;
    getTradeLogs(): Promise<Array<TradeLog>>;
    listStrategies(): Promise<Array<Strategy>>;
    toggleStrategyActive(name: string): Promise<Strategy>;
}
import type { Strategy as _Strategy, TradeLog as _TradeLog, TradeStatus as _TradeStatus, TradeType as _TradeType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTradeLog(arg0: TradeLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradeLog(to_candid_TradeLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradeLog(to_candid_TradeLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateStrategy(arg0: Strategy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateStrategy(to_candid_Strategy_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateStrategy(to_candid_Strategy_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteStrategy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStrategy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStrategy(arg0);
            return result;
        }
    }
    async getTradeLogs(): Promise<Array<TradeLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeLogs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeLogs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStrategies(): Promise<Array<Strategy>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStrategies();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStrategies();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleStrategyActive(arg0: string): Promise<Strategy> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStrategyActive(arg0);
                return from_candid_Strategy_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStrategyActive(arg0);
            return from_candid_Strategy_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Strategy_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TradeLog_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeLog): TradeLog {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TradeStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeStatus): TradeStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TradeStatus;
    tokenId: string;
    tradeType: _TradeType;
    amountToken: number;
    timestamp: bigint;
    amountBtc: number;
    price: number;
}): {
    status: TradeStatus;
    tokenId: string;
    tradeType: TradeType;
    amountToken: number;
    timestamp: bigint;
    amountBtc: number;
    price: number;
} {
    return {
        status: from_candid_TradeStatus_n12(_uploadFile, _downloadFile, value.status),
        tokenId: value.tokenId,
        tradeType: from_candid_TradeType_n14(_uploadFile, _downloadFile, value.tradeType),
        amountToken: value.amountToken,
        timestamp: value.timestamp,
        amountBtc: value.amountBtc,
        price: value.price
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    tokenId: string;
    tradeType: _TradeType;
    name: string;
    autoRepeat: boolean;
    stopLoss: number;
    maxTradeSize: number;
    priceTarget: number;
}): {
    active: boolean;
    tokenId: string;
    tradeType: TradeType;
    name: string;
    autoRepeat: boolean;
    stopLoss: number;
    maxTradeSize: number;
    priceTarget: number;
} {
    return {
        active: value.active,
        tokenId: value.tokenId,
        tradeType: from_candid_TradeType_n14(_uploadFile, _downloadFile, value.tradeType),
        name: value.name,
        autoRepeat: value.autoRepeat,
        stopLoss: value.stopLoss,
        maxTradeSize: value.maxTradeSize,
        priceTarget: value.priceTarget
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TradeStatus {
    return "pending" in value ? TradeStatus.pending : "completed" in value ? TradeStatus.completed : "failed" in value ? TradeStatus.failed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeType {
    return "buy" in value ? TradeType.buy : "sell" in value ? TradeType.sell : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Strategy>): Array<Strategy> {
    return value.map((x)=>from_candid_Strategy_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeLog>): Array<TradeLog> {
    return value.map((x)=>from_candid_TradeLog_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Strategy_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TradeLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeLog): _TradeLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TradeStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStatus): _TradeStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TradeStatus;
    tokenId: string;
    tradeType: TradeType;
    amountToken: number;
    timestamp: bigint;
    amountBtc: number;
    price: number;
}): {
    status: _TradeStatus;
    tokenId: string;
    tradeType: _TradeType;
    amountToken: number;
    timestamp: bigint;
    amountBtc: number;
    price: number;
} {
    return {
        status: to_candid_TradeStatus_n3(_uploadFile, _downloadFile, value.status),
        tokenId: value.tokenId,
        tradeType: to_candid_TradeType_n5(_uploadFile, _downloadFile, value.tradeType),
        amountToken: value.amountToken,
        timestamp: value.timestamp,
        amountBtc: value.amountBtc,
        price: value.price
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    tokenId: string;
    tradeType: TradeType;
    name: string;
    autoRepeat: boolean;
    stopLoss: number;
    maxTradeSize: number;
    priceTarget: number;
}): {
    active: boolean;
    tokenId: string;
    tradeType: _TradeType;
    name: string;
    autoRepeat: boolean;
    stopLoss: number;
    maxTradeSize: number;
    priceTarget: number;
} {
    return {
        active: value.active,
        tokenId: value.tokenId,
        tradeType: to_candid_TradeType_n5(_uploadFile, _downloadFile, value.tradeType),
        name: value.name,
        autoRepeat: value.autoRepeat,
        stopLoss: value.stopLoss,
        maxTradeSize: value.maxTradeSize,
        priceTarget: value.priceTarget
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == TradeStatus.pending ? {
        pending: null
    } : value == TradeStatus.completed ? {
        completed: null
    } : value == TradeStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeType.buy ? {
        buy: null
    } : value == TradeType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
